### ISSUE TITLE
Worked and then it didn't

### ISSUE THREAD

**Issue by Omaha2002** [nextcloud/picker#1]
First of all, thanks, great little tool for webex users.

I followed all instructions and picker worked perfectly, then I decided to delete the embedded app and create a new one with new name and icon for production.

I did exactly the same thing as the first time but now I get a "NGINX not found" error when selecting the app in webex.

![image](https://user-images.githubusercontent.com/3179748/188556941-4b7dcccf-3e2b-4d75-ad09-b32924f05dd5.png)

Deleted again the embedded app, recreated it, same result..  Pasting the URL manually in webbrowser works.

**Comment by eneiluj** [comment]
Hi. Which URL did you set as the "Start page URL"? (redact the domain name if you want).

It seems that the target webserver does not find the page so either you made a mistake in entering the URL in the embedded app settings or Webex is trying to access something else for some reason.

If you didn't delete the previous embedded app, please compare the values you've put in your embedded apps.

I might be wrong but I don't think the issue is on the picker app side.

By the way, in the webex client, you can right click in the embedded apps sidebar and hit "Inspect", then you access the embedded browser dev tools in which you have a "Network" tab to check what Webex is actually requesting.

**Comment by Omaha2002** [comment]
Ok, first of all sorry for the late response and thanks for working on the app!

As a startpage URL:
![image](https://user-images.githubusercontent.com/3179748/193771745-f7a93f81-d9fc-4480-8736-000ac2e80257.png)

The full URL is:   https://gron****.network/index.php/apps/picker/webex-single-link

Extention of the domain is .network, could that be an issue?

![image](https://user-images.githubusercontent.com/3179748/193772201-ad93115b-db48-4273-82f8-a8343fdccce1.png)

**Comment by Omaha2002** [comment]
A question about configuration, both, meetings or only messaging:

![image](https://user-images.githubusercontent.com/3179748/193787430-849c340f-7b29-4298-85d8-d970b054fd58.png)

Sidepanel or mainview?

![image](https://user-images.githubusercontent.com/3179748/193787605-430e0836-fffd-423b-910b-b07cc7a48948.png)

**Comment by Omaha2002** [comment]
Question about configuration, meeting, messaging or both?

![image](https://user-images.githubusercontent.com/3179748/193787759-43f773c3-1e7a-42fb-a9bc-eccfdd088abf.png)

Sidepanel or main view?

![image](https://user-images.githubusercontent.com/3179748/193787909-d6403976-84e9-455f-8b20-aa89d03d2758.png)

**Comment by provokateurin** [comment]
Old issue, please reopen if you still face this problem.
